### PR TITLE
Test instances

### PR DESCRIPTION
**Pull request by matiasuno**
Added FBP, K and SB test instances. Every map has at least one cell of each fuel according to its fuel model.
test.sh script find differences comparing the new results (test_results) and the "correct" results (results).

The outputs evaluated are Messages, Grids, ROS and Intensity.

### CODE REVIEW

**Comment by fdobad** [comment]
Looks good to me

**Comment by fdobad** [comment]
other flags to incorporate?
--out-fl
--out-intensity
--out-crown

--out-cfb
--out-sfb

--fmc

**Comment by matiasuno** [comment]
todo lo que sea crown sirve solo para fbp.
fl tiene el problema de que cambia independiente de la los parametros y de la seed
intensity si esta incluida.

**Review by fdobad — APPROVED** [review]
todo ok, no olvidar pendientes.

--out-fl
--out-intensity
--out-crown

--out-cfb
--out-sfb

--fmc

**Pull request merged**
